name: Build Obamium
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'
      - name: Apply Patches and Build
        run: |
            git config --global user.email "no-reply@github.com"
            git config --global user.name "GitHub Actions"
            chmod +x gradlew
            ./gradlew applyPatches --stacktrace
            ./gradlew createReobfPaperclipJar --stacktrace
